server:
  port: 9000
spring:
  application:
    name: "cards"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: "prod"

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: cards
    description: "BankLoan Cards Microservice"
    version: "1.0.0"

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka"


build:
  version: 3.0

cards:
  message: "Welcome to BankLoan cards related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@gmail.com"
  onCallSupport:
    - (555) 555-2312
    - (555) 523-4321