build:
  version: 2.0

accounts:
  message: "Welcome to BankLoan accounts related QA APIs "
  contactDetails:
    name: "Michael - QA Lead"
    email: "Michael@gmail.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345