build:
  version: 3.0

accounts:
  message: "Welcome to BankLoan accounts related default APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345