build:
  version: 3.0

cards:
  message: "Welcome to BankLoan cards related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@gmail.com"
  onCallSupport:
    - (555) 555-2312
    - (555) 523-1345