build:
  version: 1.0

cards:
  message: "Welcome to BankLoan cards related prod APIs "
  contactDetails:
    name: "Michael - Product Owner"
    email: "michael@gmail.com"
  onCallSupport:
    - (777) 555-1234
    - (777) 523-1345