spring:
  application:
    name: "Loans"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: "prod"

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "loans"
    description: "BankLoan loans related local APIs "
    version: "1.0.0"

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka"

Server:
  port: 8090

build:
  version: 3.0

loans:
  message: "Welcome to BankLoan loans related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@gmail.com"
  onCallSupport:
    - (555) 555-2312
    - (555) 523-4321
