server:
    port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
      #  native:
      #    # for class path
      #    searchLocations: classpath:/config
      # for file system path
      #    searchLocations: file:///C://ACER//BankLoanConfigServer//config

      #for github public config server
        git:
          uri: https://github.com/sahansha/BankLoanConfigServer.git
          timeout: 6
          defaultLabel: main
          cloneOnStart: true
          force-pull: true
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
#  info:
#    env:
#      enabled: true
    metrics:
      tags:
        application: ${spring.application.name}

info:
  app:
    name: "BankLoan Config Server"
    description: "BankLoan Config Server"
    version: "1.0.0"
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka

encrypt:
  key: "FD17UY18GH90BS821NBPL564"

logging:
  level:
    com:
      sahansha:
        accounts: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"